spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/eduReptile?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&jdbcCompliantTruncation=false
    username: root
    password: scott
    driver-class-name: net.sf.log4jdbc.DriverSpy
    minIdle: 5
    testOnBorrow: false
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    minEvictableIdleTimeMillis: 300000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    initialSize: 5
    maxWait: 60000
    filters: stat,wall,log4j
    logSlowSql: true
    maxActive: 20
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8090
  servlet:
    context-path: /universityReptile
